const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Timer,
		C3.Plugins.Multiplayer,
		C3.Plugins.Mouse,
		C3.Plugins.Arr,
		C3.Plugins.NinePatch,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Plugins.HTMLElement,
		C3.Plugins.Lifeasdev_MultiplayerWebsocketPlusPlugin,
		C3.Plugins.Dictionary,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.HTMLElement.Acts.SetContent,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.JavaScriptInEvents.EventDeck_Event3_Act3,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Browser.Cnds.OnUpdateFound,
		C3.Plugins.Browser.Cnds.OnUpdateReady,
		C3.Plugins.Multiplayer.Cnds.SignallingIsConnected,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.JavaScriptInEvents.EventRoomList_Event1_Act6,
		C3.Plugins.Multiplayer.Acts.SignallingAutoJoinRoom,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.Multiplayer.Cnds.SignallingIsLoggedIn,
		C3.Plugins.Multiplayer.Acts.SignallingRequestRoomList,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.EventRoomList_Event6_Act3,
		C3.Plugins.Multiplayer.Cnds.OnRoomList,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Multiplayer.Exps.ListRoomCount,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Multiplayer.Exps.ListRoomName,
		C3.Plugins.System.Exps.loopindex,
		C3.JavaScriptInEvents.EventRoomList_Event9,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.Multiplayer.Cnds.SignallingIsInRoom,
		C3.Plugins.Multiplayer.Cnds.IsReadyForInput,
		C3.Plugins.System.Cnds.Compare,
		C3.JavaScriptInEvents.EventConnecting_Event3_Act1,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.JavaScriptInEvents.EventConnecting_Event4_Act2,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Multiplayer.Acts.DisconnectRoom,
		C3.Plugins.Multiplayer.Acts.SignallingDisconnect,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.CompareVar,
		C3.JavaScriptInEvents.EventAutomatic_Event4_Act1,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.JavaScriptInEvents.EventAutomatic_Event12_Act3,
		C3.JavaScriptInEvents.EventAutomatic_Event13_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event13_Act3,
		C3.Plugins.Multiplayer.Exps.FromID,
		C3.Plugins.Arr.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Lifeasdev_MultiplayerWebsocketPlusPlugin.Cnds.onJoinedRoom,
		C3.Plugins.Lifeasdev_MultiplayerWebsocketPlusPlugin.Cnds.isHost,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.JavaScriptInEvents.EventAutomatic_Event28_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event30_Act1,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.JavaScriptInEvents.EventAutomatic_Event34_Act1,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.IsSuspended,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Lifeasdev_MultiplayerWebsocketPlusPlugin.Cnds.isInRoom,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Dictionary.Acts.DeleteKey,
		C3.Plugins.System.Exps.float,
		C3.JavaScriptInEvents.EventAutomatic_Event82_Act1,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetAngle,
		C3.JavaScriptInEvents.EventAutomatic_Event196,
		C3.Plugins.Lifeasdev_MultiplayerWebsocketPlusPlugin.Cnds.onPeerMessage,
		C3.Plugins.Lifeasdev_MultiplayerWebsocketPlusPlugin.Exps.Message,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Lifeasdev_MultiplayerWebsocketPlusPlugin.Acts.broadcastMessage,
		C3.Plugins.Lifeasdev_MultiplayerWebsocketPlusPlugin.Acts.sendPeerMessage,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Acts.SetWrapping,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.NinePatch.Cnds.IsOnScreen,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.JavaScriptInEvents.EventAutomatic_Event315_Act3,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.NinePatch.Cnds.IsVisible,
		C3.Plugins.NinePatch.Cnds.CompareZElevation,
		C3.Plugins.NinePatch.Exps.ZElevation,
		C3.JavaScriptInEvents.EventAutomatic_Event327_Act2,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.JavaScriptInEvents.EventAutomatic_Event372_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event373_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event379_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event380_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event381_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event383,
		C3.JavaScriptInEvents.EventAutomatic_Event385,
		C3.JavaScriptInEvents.EventAutomatic_Event390,
		C3.Plugins.System.Acts.Signal,
		C3.JavaScriptInEvents.EventAutomatic_Event401_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event415,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.JavaScriptInEvents.EventAutomatic_Event432,
		C3.Plugins.System.Acts.SubVar,
		C3.JavaScriptInEvents.EventAutomatic_Event452_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event453_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event455_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event455_Act3,
		C3.JavaScriptInEvents.EventAutomatic_Event456_Act5,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.JavaScriptInEvents.EventAutomatic_Event546_Act4,
		C3.Plugins.System.Exps.layoutheight,
		C3.JavaScriptInEvents.EventAutomatic_Event549,
		C3.JavaScriptInEvents.EventAutomatic_Event550_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event552_Act4,
		C3.JavaScriptInEvents.EventAutomatic_Event557,
		C3.JavaScriptInEvents.EventAutomatic_Event561,
		C3.JavaScriptInEvents.EventAutomatic_Event575_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event576_Act5,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.JavaScriptInEvents.EventAutomatic_Event593_Act1,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.JavaScriptInEvents.EventAutomatic_Event656_Act1,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.Text.Exps.PickedCount,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.NinePatch.Exps.Height,
		C3.JavaScriptInEvents.EventAutomatic_Event680_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event682_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event683_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event685_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event687_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event688_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event690_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event692_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event694_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event710_Act3,
		C3.JavaScriptInEvents.EventAutomatic_Event710_Act4,
		C3.JavaScriptInEvents.EventAutomatic_Event711_Act9,
		C3.JavaScriptInEvents.EventAutomatic_Event717_Act11,
		C3.JavaScriptInEvents.EventAutomatic_Event725,
		C3.JavaScriptInEvents.EventAutomatic_Event735,
		C3.JavaScriptInEvents.EventAutomatic_Event737,
		C3.Plugins.Text.Acts.ZMoveToObject,
		C3.Plugins.NinePatch.Acts.ZMoveToObject,
		C3.Plugins.Json.Exps.ArraySize,
		C3.JavaScriptInEvents.EventAutomatic_Event746_Act12,
		C3.JavaScriptInEvents.EventAutomatic_Event747_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event749_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event751_Act7,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.JavaScriptInEvents.EventAutomatic_Event795_Act3,
		C3.JavaScriptInEvents.EventAutomatic_Event807_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event812_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event814_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event815_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event819_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event831_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event832_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event837_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event842_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event843_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event845_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event851_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event856_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event859,
		C3.JavaScriptInEvents.EventAutomatic_Event864,
		C3.Plugins.Arr.Exps.CurX,
		C3.JavaScriptInEvents.EventAutomatic_Event868_Act3,
		C3.JavaScriptInEvents.EventAutomatic_Event869,
		C3.JavaScriptInEvents.EventAutomatic_Event870_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event874,
		C3.JavaScriptInEvents.EventAutomatic_Event879,
		C3.JavaScriptInEvents.EventAutomatic_Event883,
		C3.JavaScriptInEvents.EventAutomatic_Event887,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.JavaScriptInEvents.EventAutomatic_Event908_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event916,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.NinePatch.Acts.AddInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Dictionary.Exps.GetDefault,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.NinePatch.Exps.PickedCount,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.JavaScriptInEvents.EventAutomatic_Event979_Act2,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.JavaScriptInEvents.EventAutomatic_Event995_Act2,
		C3.JavaScriptInEvents.EventAutomatic_Event997,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.JavaScriptInEvents.EventAutomatic_Event1011_Act1,
		C3.JavaScriptInEvents.EventAutomatic_Event1011_Act3,
		C3.JavaScriptInEvents.EventAutomatic_Event1012,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.AddRemoveAnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Text.Acts.AppendText,
		C3.JavaScriptInEvents.EventAutomatic_Event1053_Act4,
		C3.Plugins.Sprite.Acts.MoveAtAngle
	];
};
self.C3_JsPropNameTable = [
	{type: 0},
	{index: 0},
	{id: 0},
	{p1: 0},
	{Anchor: 0},
	{Pin: 0},
	{Tween: 0},
	{text1: 0},
	{bg: 0},
	{state: 0},
	{p2: 0},
	{p3: 0},
	{rotation: 0},
	{string2: 0},
	{atk: 0},
	{def: 0},
	{atkChange: 0},
	{defChange: 0},
	{owner: 0},
	{damageTaken: 0},
	{from: 0},
	{number1: 0},
	{produce: 0},
	{picked: 0},
	{newMUID: 0},
	{cardImage: 0},
	{cardId: 0},
	{originalOwner: 0},
	{lockHand: 0},
	{token: 0},
	{divinity: 0},
	{rDivinity: 0},
	{DragDrop: 0},
	{Timer: 0},
	{card: 0},
	{Multiplayer: 0},
	{typeStart: 0},
	{card2: 0},
	{Mouse: 0},
	{handOver: 0},
	{zero: 0},
	{draw: 0},
	{arrDeck: 0},
	{arrSelected: 0},
	{cardUID: 0},
	{mUID: 0},
	{menu1: 0},
	{menuLine1: 0},
	{optionHover: 0},
	{cardCount: 0},
	{menu2: 0},
	{Browser: 0},
	{menu3: 0},
	{paddle: 0},
	{deckSelected: 0},
	{peepType: 0},
	{arrPeep: 0},
	{deckDrag: 0},
	{peepHide: 0},
	{button1: 0},
	{textUID: 0},
	{Text: 0},
	{Sprite: 0},
	{bg1: 0},
	{counter: 0},
	{subtype: 0},
	{counterLerp: 0},
	{over: 0},
	{JSON: 0},
	{AJAX: 0},
	{arrCardFrames: 0},
	{Keyboard: 0},
	{Flash: 0},
	{highlightCard: 0},
	{combatButton: 0},
	{tokenIcon: 0},
	{HTMLElement: 0},
	{ready: 0},
	{arrBuffer: 0},
	{MultiplayerWebsocketPlusPlugin: 0},
	{turn: 0},
	{turnLine: 0},
	{cardNMUID: 0},
	{abilityIndex: 0},
	{arrCost: 0},
	{attacker: 0},
	{defender: 0},
	{attackArrow: 0},
	{Dictionary: 0},
	{arrChase: 0},
	{arrChaseBuffer: 0},
	{arrSendBufferMessages: 0},
	{arrGetBufferMessages: 0},
	{destroy: 0},
	{Rotate: 0},
	{resolveEffect: 0},
	{resolveEffectShadow: 0},
	{Sprite2: 0},
	{cardF: 0},
	{name: 0},
	{nextType: 0},
	{p4: 0},
	{p5: 0},
	{p6: 0},
	{p7: 0},
	{message: 0},
	{relativeOwnerType: 0},
	{relativeOwnerType2: 0},
	{clientState: 0},
	{ajaxData: 0},
	{game: 0},
	{roomName: 0},
	{roomList: 0},
	{cardsJson: 0},
	{phase: 0},
	{select: 0},
	{startPlayerTurn: 0},
	{playerTurn: 0},
	{playerPriority: 0},
	{action: 0},
	{chaseSkipCount: 0},
	{myOwner: 0},
	{opponentId: 0},
	{mulliganReady: 0},
	{runesRevealed: 0},
	{gameTurn: 0},
	{deckLoaded: 0},
	{opponentSkips: 0},
	{connectionReady: 0},
	{startedOnGame: 0},
	{mainDeck: 0},
	{arrDeck2: 0},
	{arrDeck3: 0},
	{msg: 0},
	{flying: 0},
	{originKeywords: 0},
	{pick: 0},
	{origin: 0},
	{target: 0},
	{targetY: 0},
	{targetX: 0},
	{CardsInHand: 0},
	{sync: 0},
	{zoomCard: 0},
	{frame: 0},
	{visibility: 0},
	{dictionary2: 0},
	{margin: 0},
	{offset: 0},
	{x: 0},
	{halfCard: 0},
	{count: 0},
	{arr: 0},
	{originalY: 0},
	{originalX: 0},
	{y: 0},
	{columns: 0},
	{posInBlock: 0},
	{block: 0},
	{rowIndex: 0},
	{columnIndex: 0},
	{top: 0},
	{cardImageTop: 0},
	{input: 0},
	{normal: 0},
	{disableOver: 0},
	{option: 0},
	{text: 0},
	{cardPickCount: 0},
	{counterTypeChoose: 0},
	{willType: 0},
	{cx: 0},
	{canPay: 0},
	{optionalChoose: 0},
	{endTurn: 0},
	{resolving: 0},
	{wait: 0},
	{roll: 0},
	{icon: 0},
	{arrType: 0},
	{resolveType: 0},
	{trigger: 0},
	{resolveStringify: 0},
	{active: 0},
	{checked: 0},
	{cardD: 0},
	{lp1: 0},
	{lp2: 0},
	{stringify: 0},
	{costCount: 0},
	{cost: 0},
	{optional: 0},
	{forceResolve: 0},
	{r: 0},
	{cardDataStringify: 0},
	{cardMUID: 0},
	{options: 0},
	{canAttack: 0},
	{deckType: 0},
	{total: 0},
	{gap: 0},
	{rightIndex: 0},
	{leftIndex: 0},
	{leftCenter: 0},
	{rightCenter: 0},
	{cardID: 0},
	{handleChase: 0},
	{cardOwner: 0},
	{cardDivinity: 0},
	{skillIndex: 0},
	{cardsIndex: 0},
	{cardsUID: 0},
	{dictionary: 0},
	{enable: 0},
	{attack: 0},
	{vars: 0},
	{stepVars: 0},
	{pop: 0},
	{step: 0},
	{resolve: 0},
	{pile: 0},
	{countersString: 0},
	{pickCard: 0},
	{filters: 0},
	{cardsId: 0},
	{other: 0},
	{initialIndex: 0},
	{group: 0},
	{selectOption: 0},
	{judgement: 0},
	{energize: 0},
	{counterType: 0},
	{amount: 0},
	{player: 0},
	{counterCount: 0},
	{keyword: 0},
	{value: 0},
	{originCardUID: 0},
	{targetCardUID: 0},
	{add: 0},
	{toggleable: 0},
	{originX: 0},
	{originY: 0},
	{nextUID: 0},
	{dataCard: 0},
	{originMUID: 0},
	{ratio: 0},
	{containerX: 0},
	{paddleWidth: 0},
	{containerWidth: 0},
	{containerViewWidth: 0},
	{visible: 0},
	{load: 0},
	{color: 0}
];

self.InstanceType = {
	text1: class extends self.ISpriteFontInstance {},
	bg: class extends self.ISpriteInstance {},
	card: class extends self.ISpriteInstance {},
	Multiplayer: class extends self.IInstance {},
	card2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	handOver: class extends self.ISpriteInstance {},
	arrDeck: class extends self.IArrayInstance {},
	menu1: class extends self.I9PatchInstance {},
	menuLine1: class extends self.ISpriteInstance {},
	optionHover: class extends self.ISpriteInstance {},
	menu2: class extends self.I9PatchInstance {},
	Browser: class extends self.IInstance {},
	menu3: class extends self.I9PatchInstance {},
	paddle: class extends self.ISpriteInstance {},
	arrPeep: class extends self.IArrayInstance {},
	deckDrag: class extends self.ISpriteInstance {},
	peepHide: class extends self.ISpriteInstance {},
	button1: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bg1: class extends self.ISpriteInstance {},
	over: class extends self.I9PatchInstance {},
	JSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	arrCardFrames: class extends self.IArrayInstance {},
	cardImage: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	highlightCard: class extends self.ISpriteInstance {},
	combatButton: class extends self.ISpriteInstance {},
	tokenIcon: class extends self.ISpriteInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	arrBuffer: class extends self.IArrayInstance {},
	MultiplayerWebsocketPlusPlugin: class extends C3.Plugins.Lifeasdev_MultiplayerWebsocketPlusPlugin.Instance {},
	turnLine: class extends self.ISpriteInstance {},
	arrCost: class extends self.IArrayInstance {},
	attackArrow: class extends self.I9PatchInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	arrChase: class extends self.IArrayInstance {},
	arrChaseBuffer: class extends self.IArrayInstance {},
	arrSendBufferMessages: class extends self.IArrayInstance {},
	arrGetBufferMessages: class extends self.IArrayInstance {},
	resolveEffect: class extends self.ISpriteInstance {},
	resolveEffectShadow: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	cardF: class extends self.ISpriteInstance {}
}